version: '2'

volumes:
  mysqldata:
    driver: local

services:
  d4dapp:
    build: ./docker/
    environment:
      MYSQL_HOST: 'mysqlserver'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 's3curep@assword'
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dockerfordevs
    volumes:
      - ./:/var/www/
    ports:
      - 8080:80

  testrunner:
    build: ./docker/
    volumes:
      - ./:/app
    working_dir: /app
    command: vendor/bin/phpunit -c .

  mysqlserver:
    image: mysql
    environment:
      MYSQL_DATABASE: dockerfordevs
      MYSQL_ROOT_PASSWORD: 's3curep@assword'
    volumes:
      - mysqldata:/var/lib/mysql